### ISSUE TITLE
As an SBA user I need to upload my data files to the website

### ISSUE THREAD

**Issue by bsweger** [18F/data-act-pilot#101]
Acceptance Criteria:

- [x] Web app can receive one or more files from the user
- [x] Web app provides confirmation that files have been received

**Comment by msecret** [comment]
Question: Will we be permanently storing the data files or any other user information?

**Comment by bsweger** [comment]
Yes, we'd previously discussed storing the data files locally. They don't have any PII, as the point of DATA Act is to publish this info (in fact, much of it is already out there on USAspending.gov).

As for user info, I don't think we have to worry about that for this sprint. In the future (perhaps even post-pilot), it probably makes sense to capture userid or something, but not yet.
