### ISSUE TITLE
As an SBA user, I need to be able to access the web app remotely

### ISSUE THREAD

**Issue by bsweger** [18F/data-act-pilot#103]
Acceptance criteria:

- [ ] Web app is online and accessible via web
- [ ] Web app is password protected

**Comment by msecret** [comment]
- [ ] Encrypt my hard drive for cloud foundry access.
- [ ] Ask dev ops for cloud foundry access.
- [ ] Figure out ATO.
- [ ] Configure cloud foundry for python app.
- [ ] Configure cloud foundry to serve static files.

Depends on #90
