### ISSUE TITLE
As an SBA user, I need the submission process to inform me if my file is not formatted in one of the four CSV formats

### ISSUE THREAD

**Issue by micahsaul** [18F/data-act-pilot#110]
Acceptance Criteria

- [x]  Prior to any other validation, a submission should be rejected if it is not in one of the four proposed aggregation formats.

**Comment by msecret** [comment]
I think the plan here was to just validate the CSV for a set of columns. How would I find what the required columns would be?

**Comment by bsweger** [comment]
Great question--right now, the four .csv templates (with column names) are sitting in an unmerged branch: https://github.com/18F/data-act-pilot/tree/split-file-template/template

(see the files named inventory_mapping_*.csv, but I'm going to rename them to the names on Andrew's wireframe)

Treasury is working on new set of column names (there's several versions floating around), and we should have those early next week. Not sure how that impacts your decision to move forward here.

**Comment by msecret** [comment]
@andrewmaier the three potential error conditions that I have now are:

- File wasn't uploaded at all
- File isn't of `.csv` type
- File has incorrect headers.

Do we want the UI to display these types of errors? If so, you can let me know what you're thinking, I don't necessarily need a design.

**Comment by bsweger** [comment]
FWIW, I think the UI should display these types of errors

**Comment by andrewmaier** [comment]
(File wasn't uploaded at all) ||
(File isn't of .csv type) ||
(File has incorrect headers) ===
 File wasn't able to be read

?

**Comment by msecret** [comment]
Yes, that sounds right
