### ISSUE TITLE
As an agency user, I need a refined experience on the broker website

### ISSUE THREAD

**Issue by bsweger** [18F/data-act-pilot#150]
Acceptance criteria:

- [x] Visually distinguish between error messages coming out of the four files
- [x] Clean up website copy
- [x] Incorporate Government-wide Pattern Library components

**Comment by elainekamlley** [comment]
Draft of the app copy: https://docs.google.com/document/d/1e-7It46qEfba71KD294B0gsgLWKbtlI0w-PqO1jadnc/edit
