### ISSUE TITLE
As an agency user, I would like an updated screencast that includes the data conversion part of the broker process

### ISSUE THREAD

**Issue by bsweger** [18F/data-act-pilot#168]
Acceptance criteria:

- [x] Same content as screencast created for #147
- [x] Add demo of the actual data conversion
- [x] Replaces the current screencast in the project repository
- [x] Viewable by a large audience (including people with older versions of Windows Media Player) without special software

**Comment by bsweger** [comment]
Should the list of links at the end include Treasury's DATA Act e-mail address?

**Comment by bsweger** [comment]
Elaine created a version of the 1st screencast that cuts off before the web demo begins--this will be the starting point for the next version. Will re-record the web demo and add a bit of intro as suggested by Elaine.

**Comment by elainekamlley** [comment]
Updated links here: https://github.com/18F/data-act-pilot/tree/master/assets/screencast
