### ISSUE TITLE
Bug: sample data file has two instances of the field "BusinessTypes".

### ISSUE THREAD

**Issue by yehk** [18F/data-act-pilot#236]
Acceptance Criteria:
- [ ] Remove the second instance of BusinessType from sample files (the one without "s" at end)

**Comment by bsweger** [comment]
Thanks @yehk! There's a patch for this in pull request #235 (which also adds the dummy files to the repo). When @micahsaul reviews and merges that code, this bug should be fixed (and will auto close).
