### ISSUE TITLE
.zip of dummy data looks out of date

### ISSUE THREAD

**Issue by bsweger** [18F/data-act-pilot#252]
Just a heads up that the old .zip of the dummy data files is still in the repo: https://github.com/18F/data-act-pilot/blob/master/data/dummy/data-broker-all-dummy-files.zip

I'd recommend removing it if there aren't plans to keep it up to date--the direct link might still be floating around in some e-mails, leading people to an old information.

(we originally put the .zip out there as an easy way to link people to all four files)

**Comment by yehk** [comment]
Hi Becky,


 


 Are you back from leave? If so, welcome back!


 I do agree the file needs to be either removed or replaced. I will follow up on it.


 


 Thanks,


 Kristina
 

 
 
   
 
 
  From: Becky Sweger
 
 
  Sent: Thursday, February 4, 2016 2:58 PM
 
 
  To: 18F/data-act-pilot
 
 
  Reply To: 18F/data-act-pilot
 
 
  Subject: [data-act-pilot] .zip of dummy data looks out of date (#252)
 




 Just a heads up that the old .zip of the dummy data files is still in the repo: https://hyperlink.services.treasury.gov/?origin=https://github.com/18F/data-act-pilot/blob/master/data/dummy/data-broker-all-dummy-files.zip 
 I'd recommend removing it if there aren't plans to keep it up to date--the direct link might still be floating around in some e-mails, leading people to an old information. 
 (we originally put the .zip out there as an easy way to link people to all four files)

**Comment by kaitlin** [comment]
The zip was updated. Gonna close this for now.
