### ISSUE TITLE
As an SBA user, I need to understand how my award-level data aggregates to financial system DATA Act elements

### ISSUE THREAD

**Issue by bsweger** [18F/data-act-pilot#31]
Want to make sure we don't forget about this. It's possible that any required aggregations will happen on the Treasury side, and that agencies won't have to handle the aggregation question. It's also possible that Treasury will just publish data at the atomic level, but that seems unlikely. I assume there will have to be some way to show total outlays, budget authority, and payments by account/program.

Acceptance Criteria:

- [ ] Add aggregate rules/info to existing business rules doc
- [ ] Update data act schema representation to reflect aggregations
- [ ] Document whether or not we can tie financials to individual award modifications

Tasks:

- [x] Determine the "level" of GTAS data we have in the current extracts
- [ ] Determine if there's a Prism field that ties back to award modification
- [ ] Compare award-level aggregates to their financial-level counterparts
- [ ] Update the business rules doc
- [x] Get a high-level overview of Oracle Financials

**Comment by yehk** [comment]
Replaced with story 100.
