### ISSUE TITLE
As an SBA user, I need feedback about the validity of my data act file

### ISSUE THREAD

**Issue by bsweger** [18F/data-act-pilot#5]
Acceptance Criteria:

- [x] Document at what point in the process validations occur
- [x] Document what happens when data does not validate. Hard stop? Are there different severity levels that would trigger different processes?
- [x] SBA user can submit a DATA Act-formatted file to a validation process
- [x] Validation process will return accepted/rejected status to SBA user
- [x] Validation process will return high-level metadata about the submitted DATA Act file (e.g., total number of rows, total rows passing validation, total rows failing validation, last change date for the rules that drive the validation process)
- [x] Validation process will return specific error details for each row that fails validation (if any)

Tasks:

- [ ]

**Comment by bsweger** [comment]
See research question #73

**Comment by bsweger** [comment]
@elainekamlley After you're done updating the validation script, can you add info about running it to README.md and INSTALL.md (there's a sample list of commands at the bottom)? Thanks!

**Comment by bsweger** [comment]
Feedback: include the award and mod # when printing the validation errors, so people can easily track it back to the source system

**Comment by elainekamlley** [comment]
Sent revised validation errors for review as per feedback. Pushed up code to the GitHub repo  to reflect these changes.

**Comment by bsweger** [comment]
Need to emphasize the usability of this as we move to the web
