### ISSUE TITLE
As an SBA user, I need requirements for the file types and formats that will be submitted to Treasury's validation process

### ISSUE THREAD

**Issue by bsweger** [18F/data-act-pilot#51]
For example, will there be separate file submissions for awards-level and financial data? Will there be separate submissions for different types of awards (e.g., grants, contracts).? Will we just sent one wide file? What file type/format will be required?

Acceptance Criteria:
- [x] Decision: one file or multiple files
- [x] If multiple files, how will we know which data goes in each file?
- [x] Decision: file format (.csv or something else)
- [ ] Document attributes needed in the file (e.g., if .csv, column names, length)
- [x] English description of decision points
- [x] Sample file(s)

**Comment by bsweger** [comment]
First pass lives here: https://github.com/18F/intercessor/blob/master/process.md

Got some great feedback that it would be best to have all award types in a single file, which will enable a "sanity check" (not a "reconciliation") with GTAS.

**Comment by bsweger** [comment]
Update the validation rules to accommodate the single file format.
Make sample file with generic field names

**Comment by bsweger** [comment]
As part of work for #61, moved process.md to the new template folder and updated it to reflect that we're now thinking one single submission file regardless of award type.

**Comment by bsweger** [comment]
Note: in process of scheduling a check-in with Oliver and Mindy, who have some thoughts based on working with other agencies.

**Comment by yehk** [comment]
Replaced with story 100.
