### ISSUE TITLE
As an SBA user, I need a template that can be used for mapping agency financial/award data to the DATA Act schema

### ISSUE THREAD

**Issue by bsweger** [18F/data-act-pilot#61]
This is based on feedback and lessons learned from using the original mapping spreadsheet in the SBA pilot. 

Acceptance criteria:
- [x] Template has the DATA Act elements sorted into logical groups (see the [collaboration space](http://fedspendingtransparency.github.io/dataelements/)).
- [x] Template links to a visual representation of the relationships between the DATA Act elements (i.e., the schema)
- [x] Each element in the mapping template links to the finalized data element definition (where possible) or the white paper of the proposed definition
- [x] Template has information about available resources for agency questions/help

Tasks:
- [x] Create ERD of the "mock" DATA Act schema
- [x] Digest the various in-progress docs for agency DATA Act guidance

**Comment by bsweger** [comment]
Treasury will send draft of latest playbook draft.

**Comment by bsweger** [comment]
Becky: will do ERD of the "mock" DATA Act schema we're using (i.e., criteria 2)

**Comment by elainekamlley** [comment]
Elaine: will look over the latest playbook and other docs and create a simplified document with SBA specific information.

**Comment by bsweger** [comment]
Also, see #62

**Comment by bsweger** [comment]
WIP in this branch: https://github.com/18F/data-act-pilot/tree/61-template

**Comment by bsweger** [comment]
Neeraj passed along this example of how we might publish schema information (not entirely relevant to this story, but didn't want to lose it): https://project-open-data.cio.gov/
