### ISSUE TITLE
more business rule info

### ISSUE THREAD

**Issue by bsweger** [18F/data-act-pilot#82]
@elainekamlley Combing through some old issues/notes and have a few additions for the biz rules (see below). I can put the info below into a WIP PR but won't start that until I hear from you--want to make sure I'm not stepping on any local work you're doing.

Thoughts:
* Change **Awardee validation** section to **Award validation** and add these new validations to it:
    * _Type of Transaction Code_, which should be one of the values listed here: http://fedspendingtransparency.github.io/whitepapers/type-transaction-code/ (see FAADS+, type of transaction code)
    * _Record Type_: must be '1' or '2' (based on [draft whitepaper](http://fedspendingtransparency.github.io/whitepapers/type-transaction-code/))
    * _Type of Action_: must be 'B', 'C', or 'D' (based on [draft whitepaper](http://fedspendingtransparency.github.io/whitepapers/type-transaction-code/))

* An addition to the questions list: what are the applicable transaction codes for contract data?

**Comment by elainekamlley** [comment]
Thanks Becky! I'll go ahead and add these.
